org: tejnc
app: chat
service: chat

frameworkVersion: '2'


provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

plugins:
  - serverless-offline

functions:
  - ${file(functions/index.yml)}


